//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGA
    {
        public int Film_Id { get; set; }
        public int Genre_Id { get; set; }
        public int Actor_Id { get; set; }
    
        public virtual Actors Actors { get; set; }
        public virtual Films Films { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
